"""empty message

Revision ID: 261a052c4bb2
Revises: cf0c77fe5188
Create Date: 2022-07-30 12:16:41.939808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261a052c4bb2'
down_revision = 'cf0c77fe5188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferenceservice', sa.Column('inference_config', sa.Text(length=65536), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inferenceservice', 'inference_config')
    # ### end Alembic commands ###
