"""empty message

Revision ID: 430787047244
Revises: d327fd496e47
Create Date: 2022-07-20 06:44:56.408126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '430787047244'
down_revision = 'd327fd496e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kfservice')
    op.add_column('inferenceservice', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('nni', sa.Column('job_worker_command', sa.String(length=200), nullable=True))
    op.add_column('nni', sa.Column('job_worker_image', sa.String(length=200), nullable=True))
    op.alter_column('nni', 'job_type',
               existing_type=mysql.ENUM('Job'),
               nullable=True)
    op.alter_column('nni', 'namespace',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nni', 'namespace',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('nni', 'job_type',
               existing_type=mysql.ENUM('Job'),
               nullable=False)
    op.drop_column('nni', 'job_worker_image')
    op.drop_column('nni', 'job_worker_command')
    op.drop_column('inferenceservice', 'priority')
    op.create_table('kfservice',
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('changed_on', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('service_type', mysql.ENUM('predictor', 'transformer', 'explainer'), nullable=False),
    sa.Column('default_service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('canary_service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('canary_traffic_percent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['canary_service_id'], ['service.id'], name='kfservice_ibfk_1'),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], name='kfservice_ibfk_2'),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], name='kfservice_ibfk_3'),
    sa.ForeignKeyConstraint(['default_service_id'], ['service.id'], name='kfservice_ibfk_4'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='kfservice_ibfk_5'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
