"""empty message

Revision ID: cf0c77fe5188
Revises: bbe894fbed76
Create Date: 2022-07-27 14:39:13.631511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0c77fe5188'
down_revision = 'bbe894fbed76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('price', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'price')
    # ### end Alembic commands ###
