"""empty message

Revision ID: e67a0279fca9
Revises: 388613a8879c
Create Date: 2022-07-21 07:18:17.605546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67a0279fca9'
down_revision = '388613a8879c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sqllchemy_uri', sa.String(length=255), nullable=True),
    sa.Column('src_db', sa.String(length=255), nullable=True),
    sa.Column('syn_db', sa.String(length=255), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('describe', sa.String(length=2000), nullable=True),
    sa.Column('app', sa.String(length=255), nullable=True),
    sa.Column('dev_owner', sa.String(length=2000), nullable=True),
    sa.Column('app_owner', sa.String(length=2000), nullable=True),
    sa.Column('write_owner', sa.String(length=2000), nullable=True),
    sa.Column('columns', sa.Text(), nullable=True),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_desc', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_table('tdw_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=200), nullable=True),
    sa.Column('app', sa.String(length=200), nullable=True),
    sa.Column('c_org_fullname', sa.String(length=255), nullable=True),
    sa.Column('db', sa.String(length=200), nullable=True),
    sa.Column('table', sa.String(length=400), nullable=True),
    sa.Column('metadata_column', sa.Text(), nullable=True),
    sa.Column('describe', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('lifecycle', sa.Integer(), nullable=True),
    sa.Column('rec_lifecycle', sa.Integer(), nullable=True),
    sa.Column('storage_size', sa.String(length=200), nullable=True),
    sa.Column('storage_cost', sa.Float(), nullable=True),
    sa.Column('visits_seven', sa.Integer(), nullable=True),
    sa.Column('visits_thirty', sa.BigInteger(), nullable=True),
    sa.Column('visits_sixty', sa.BigInteger(), nullable=True),
    sa.Column('recent_visit', sa.Date(), nullable=True),
    sa.Column('partition_start', sa.String(length=255), nullable=True),
    sa.Column('partition_end', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.String(length=255), nullable=True),
    sa.Column('create_table_ddl', sa.Text(), nullable=True),
    sa.Column('col_info', sa.Text(), nullable=True),
    sa.Column('partition_update_mode', sa.Integer(), nullable=True),
    sa.Column('is_privilege', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('security_level', sa.String(length=200), nullable=True),
    sa.Column('value_score', sa.String(length=200), nullable=True),
    sa.Column('warehouse_level', sa.String(length=200), nullable=True),
    sa.Column('ttl', sa.String(length=200), nullable=True),
    sa.Column('insert_sql', sa.Text(length=65536), nullable=True),
    sa.Column('crontab', sa.String(length=200), nullable=True),
    sa.Column('task_id', sa.String(length=200), nullable=True),
    sa.Column('expand', sa.Text(length=65536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_metric',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('describe', sa.String(length=500), nullable=False),
    sa.Column('caliber', sa.Text(length=65536), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=True),
    sa.Column('metric_level', sa.String(length=100), nullable=True),
    sa.Column('metric_dim', sa.String(length=100), nullable=True),
    sa.Column('metric_data_type', sa.String(length=100), nullable=True),
    sa.Column('metric_responsible', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('task_id', sa.String(length=200), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('expand', sa.Text(length=65536), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_metric')
    op.drop_table('tdw_metadata')
    op.drop_table('dimension')
    # ### end Alembic commands ###
